---
title: "InititalAnalysis"
author: "Antonia"
date: "12 11 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(knitr)
library(stringr)
```


```{r load}
data = read.csv("data.csv", sep = ";")
```



```{r}
colnames(data)

data = data[ , order(names(data))]
#colnames(data)

modelNames = word(colnames(data),1, sep = "\\_")
paramNames = sub('.*\\_', '', colnames(data))

numParamModel = summary(as.factor(modelNames))

```

```{r, correlationWitthinModels}

 ### create array Model Name, number Parameters,max(abs(cor)), mean(abs(cor))  

CorrModelParams = as.data.frame(NA, nrow = c(length(unique(modelNames))), ncol= 4)
accNumbParams = 0 # strting index for columbs in data
for (m in 1:length(unique(modelNames))){
datatemp = data[,(accNumbParams+1) : (accNumbParams + as.numeric(numParamModel[unique(modelNames)[m]]))]
#print(colnames(datatemp))

CorrModelParams[m,1] = unique(modelNames)[m]
CorrModelParams[m,2] = numParamModel[unique(modelNames)[m]]
if (numParamModel[unique(modelNames)[m]] > 1) {
  
  print(kable(round(cor(datatemp),2)))
cors = abs(cor(datatemp))
cors[cors == 1] = NA

CorrModelParams[m,3] = max(cors, na.rm = T)
CorrModelParams[m,4] = mean(cors, na.rm = T)
}
accNumbParams = cumsum(numParamModel)[m]
}

colnames(CorrModelParams) = c("Name", "nPars", "maxnCor", "meanCor")


```


```{r}

library(stringr)
Sigmas = str_detect(colnames(data), "sigma")
Epsilons = str_detect(colnames(data), "epsilon")
CPT = str_detect(colnames(data), "CPT")
Gammas = str_detect(colnames(data), "gamma")
## Mean correlation of model specific epsilon, wiht other epsilons ___ must consider rank order correlation
EpsilonsCorr = apply(abs(cor(data[,which(Epsilons == T)], method = "spearman")),2,mean)
kable(round(cor(data[,which(Epsilons == T)]),2))
EpsilonsCorr
GammasCorr = apply(abs(cor(data[,which(Gammas == T)], method = "spearman")),2,mean)
kable(round(cor(data[,which(Gammas == T)]),2))
GammasCorr

# 
# ## Mean absolute Param Correlations in Models with Epsilon
plot(CorrModelParams[CorrModelParams$Name %in% modelNames[which(Epsilons == T)],4],EpsilonsCorr)

plot(CorrModelParams[CorrModelParams$Name %in% modelNames[which(Gammas == T)],4],GammasCorr)
CorrModelParams[!(CorrModelParams$Name %in% modelNames[which(Epsilons == T)]),4]
# 
# ## Mean absolute Param Correlations in Models with Gamma
# CorrModelParams[CorrModelParams$Name %in% modelNames[which(Gammas == T)],4]
# CorrModelParams[!(CorrModelParams$Name %in% modelNames[which(Gammas == T)]),4]





```